services:
  web:
    build:
      context: ./app
    container_name: flask-app
    restart: always
    depends_on:
      - redis
    networks:
      - app-net
  
  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-net
      
  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - web
    networks:
      - app-net
      
volumes:
  redis-data:
  
networks:
  app-net:
    
