apiVersion: v1
kind: Service
metadata:
  name: visitor-service
spec:
  selector:
    app: visitor
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

